name: Step 3b # Copilot Agent Mode

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  actions: write
  issues: write

env:
  # Keywords required in the issue comment to allow this workflow to run
  STEP_3B_FILE: ".github/steps/3b-copilot-agent-mode.md"

jobs:
  check_keywords:
    name: Check issue comment text for required keyword
    runs-on: ubuntu-latest
    steps:
      - name: Check for professortocat reference
        id: check_professortocat
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "professortocat"
          case-sensitive: false
          minimum-occurrences: 1
      - name: Check for alert reference
        id: check_alert
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "agent"
          case-sensitive: false
          minimum-occurrences: 1

  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_keywords]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_3B_FILE }}

      - name: Disable current workflow
        run: |
          gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
